Program
..FuncDefinition
....Int
....Id(main)
....ParamList
......ParamDeclaration
........Void
....FuncBody
......Declaration
........Char
........Id(i)
........ChrLit('A')
......Declaration
........Char
........Id(a)
........ChrLit('A')
......Return
........IntLit(0)
